### ISSUE TITLE
PERL WARNING bringt FHEM zum Absturz

### ISSUE THREAD

**Issue by DerDoubleD** [klein0r/fhem-abstracttable#1]
2019.03.07 19:30:03 1: PERL WARNING: Use of uninitialized value $currentRow[1] in join or string at ./FHEM/98_abstracttable.pm line 105.

`define tabelle_arbeitszahlen abstracttable WaermepumpeWertesammler
setuuid tabelle_arbeitszahlen 5c816033-f33f-221a-a1ea-94eed3f1f3fd2c0a
attr tabelle_arbeitszahlen room 30_Technik->Waermepumpe
attr tabelle_arbeitszahlen table-header Verbrauch,Arbeitszahl,Soli_min,Waermemenge,Tackte Hz,Tackt WWZirk,Verdichter Starts
attr tabelle_arbeitszahlen table-rowtemplate StromverbrauchWaermepumpeTag_vor_%d_Tagen,ArbeitszahlTag_vor_%d_Tagen,SoleaustrittTagMinTemp_vor_%d_Tagen,WaermemengeGesamtTag_vor_5d_Tagen,TacktHzTag_vor_%d_Tagen,TacktZirkWwTag_vor_%d_Tagen,VerdichterStartsTag_vor_%d_Tagen`

**Comment by klein0r** [comment]
Sollte nach dem Update nicht mehr kommen. War aber eigentlich nur eine Warning - FHEM sollte davon nicht abstürzen?
