### ISSUE TITLE
Sortierung

### ISSUE THREAD

**Issue by DuschdrBabbe** [klein0r/fhem-abstracttable#3]
Hi,

ich möchte gerne noch eine Sortierung durchführen, wie mache ich das?
Möchte eine Spalte angeben und wie rum sortiert werden soll....

*edit* cool währe es wenn man auch 2 oder mehr Spalten angeben könnte... 

Grüßle

Pascal

**Comment by klein0r** [comment]
Das Modul habe ich nur mal grob angefangen und nutze es für diverse Übersichten. Die Reihenfolge wird aktuell nur durch die Reihenfolge der Readings vorgegeben. Eine Sortierung ist zur Zeit nicht möglich. Ich denke nicht, dass ich da so schnell Zeit für finden werde. Ansonsten gerne einen Pull Request einreichen

**Comment by PatricSperling** [comment]
Ich hab mir die Zeit mal genommen.
Es wird allerdings immer alphanumerisch sortiert.
Siehe pull request.
